import os
import subprocess

from common_code import git_utils 

punctuations = ".`'\",:;!?@#$%^&*({)[]{}/\\"
punctuation_dictionary = { ord(ch): None for ch in punctuations}

def remove_punctuation(input):
    return input.translate(punctuation_dictionary)

dir = input("Please give the directory to analyze: ")
os.chdir(dir)
message_file = input("Please give the name for the .txt file to create: ") + ".txt"

git_utils.create_abbreviated_log(message_file)

temp_file = "git_log_" + message_file # default name of file generated by git_utils.create*log

lowercased_text = ""
with open(temp_file) as f:
    for line in f:
        lowercased_text += remove_punctuation(line.lower())

output_file = open(message_file, "w")
output_file.write(lowercased_text)
os.remove(temp_file)
print(f"Please upload '{message_file}' to https://wordart.com/ .")

